### PR TITLE
Use golang:1.10.3-alpine3.7 for buildtool-alpine

### PR DESCRIPTION
**Pull request by UladzimirTrehubenka**

### CODE REVIEW

**Comment by dkamenda** [comment]
I am OK with the changes.

**Comment by dkamenda** [comment]
@sastryv , could you please advice anybody with the permission to review/check-in here. Thanks!

**Comment by dkamenda** [comment]
@sastryv , just a friendly reminder: is there anybody with write access to the repo who can review and merge this one? Thanks.

**Review by dkamenda — APPROVED** [review]

**Review by vasily-chertkov — APPROVED** [review]

**Comment by dkamenda** [comment]
@UladzimirTrehubenka permissions have been granted now, is the PR still actual?

**Comment by UladzimirTrehubenka** [comment]
PR is still actual - so could someone merge it and build fresh image (infoblox/buildtool-alpine:latest)?

**Pull request merged**
